// <auto-generated />
using System;
using Lumora.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumora.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706071352_UpdatedBaseEntity")]
    partial class UpdatedBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotographyStyle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SelectedStudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecialRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumerProfileId");

                    b.HasIndex("SelectedStudioId");

                    b.HasIndex("Status");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Gallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ExternalProvider")
                        .HasColumnType("integer");

                    b.Property<string>("FolderLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GalleryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GalleryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAt");

                    b.HasIndex("ExternalProvider");

                    b.HasIndex("GalleryStatus");

                    b.HasIndex("InquiryId")
                        .IsUnique();

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionStatus")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudioProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumerProfileId");

                    b.HasIndex("EventId");

                    b.HasIndex("Status");

                    b.HasIndex("StudioId");

                    b.HasIndex("StudioProfileId");

                    b.HasIndex("StudioId", "EventId", "ConsumerId")
                        .IsUnique();

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.ConsumerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ConsumerProfiles");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.StudioProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudioName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudioProfiles");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorBackupCodes")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("INR");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazorPayOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RazorePaySignature")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudioProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("InquiryId")
                        .IsUnique();

                    b.HasIndex("RazorPayOrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StudioId");

                    b.HasIndex("StudioProfileId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InquiryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudioProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("ConsumerProfileId");

                    b.HasIndex("EventId");

                    b.HasIndex("InquiryId")
                        .IsUnique();

                    b.HasIndex("Rating");

                    b.HasIndex("StudioId");

                    b.HasIndex("StudioProfileId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Studio.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("StudioId");

                    b.HasIndex("Email", "Phone")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Tag.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("StudioTags", b =>
                {
                    b.Property<Guid>("StudiosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("StudiosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("StudioTags");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Event", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.ConsumerProfile", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.ConsumerProfile", null)
                        .WithMany("Events")
                        .HasForeignKey("ConsumerProfileId");

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", "SelectedStudio")
                        .WithMany()
                        .HasForeignKey("SelectedStudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Lumora.Domain.Entities.Common.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1
                                .ToJson("Location")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.OwnsOne("Lumora.Domain.Entities.Event.ValueObjects.EventCategory", "EventCategory", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("event_category_type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("event_category_value");

                            b1.HasKey("EventId");

                            b1.ToTable("Events");

                            b1.WithOwner()
                                .HasForeignKey("EventId");
                        });

                    b.Navigation("Consumer");

                    b.Navigation("EventCategory")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("SelectedStudio");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Gallery", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Event.Inquiry", "Inquiry")
                        .WithOne("Gallery")
                        .HasForeignKey("Lumora.Domain.Entities.Event.Gallery", "InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Inquiry", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.ConsumerProfile", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.ConsumerProfile", null)
                        .WithMany("Inquiry")
                        .HasForeignKey("ConsumerProfileId");

                    b.HasOne("Lumora.Domain.Entities.Event.Event", "Event")
                        .WithMany("Inquiries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", null)
                        .WithMany("Inquiries")
                        .HasForeignKey("StudioProfileId");

                    b.Navigation("Consumer");

                    b.Navigation("Event");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.ConsumerProfile", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.User", null)
                        .WithOne("ConsumerProfile")
                        .HasForeignKey("Lumora.Domain.Entities.Identity.ConsumerProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("Lumora.Domain.Entities.Identity.ConsumerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.StudioProfile", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.User", null)
                        .WithOne("StudioProfile")
                        .HasForeignKey("Lumora.Domain.Entities.Identity.StudioProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.User", "User")
                        .WithOne()
                        .HasForeignKey("Lumora.Domain.Entities.Identity.StudioProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lumora.Domain.Entities.Common.ValueObjects.ServiceRadius", "ServiceRadius", b1 =>
                        {
                            b1.Property<Guid>("StudioProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Distance")
                                .HasColumnType("double precision");

                            b1.Property<int>("RadiusType")
                                .HasColumnType("integer");

                            b1.HasKey("StudioProfileId");

                            b1.ToTable("StudioProfiles");

                            b1
                                .ToJson("ServiceRadius")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudioProfileId");
                        });

                    b.OwnsOne("Lumora.Domain.Entities.Common.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<Guid>("StudioProfileId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("StudioProfileId");

                            b1.ToTable("StudioProfiles");

                            b1
                                .ToJson("Location")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudioProfileId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("ServiceRadius")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.User", b =>
                {
                    b.OwnsOne("Lumora.Domain.Entities.Common.ValueObjects.SuspensionInfo", "SuspensionInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsSuspended")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("SuspendedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("SuspendedBy")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("SuspendedTill")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("SuspensionReason")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1
                                .ToJson("SuspensionInfo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("SuspensionInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Payments.Payment", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Event.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Event.Inquiry", "Inquiry")
                        .WithOne("Payment")
                        .HasForeignKey("Lumora.Domain.Entities.Payments.Payment", "InquiryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", null)
                        .WithMany("Payments")
                        .HasForeignKey("StudioProfileId");

                    b.Navigation("Event");

                    b.Navigation("Inquiry");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Reviews.Review", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.ConsumerProfile", "Consumer")
                        .WithMany()
                        .HasForeignKey("ConsumerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.ConsumerProfile", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ConsumerProfileId");

                    b.HasOne("Lumora.Domain.Entities.Event.Event", null)
                        .WithMany("Reviews")
                        .HasForeignKey("EventId");

                    b.HasOne("Lumora.Domain.Entities.Event.Inquiry", "Inquiry")
                        .WithMany("Reviews")
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StudioProfileId");

                    b.Navigation("Consumer");

                    b.Navigation("Inquiry");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Studio.Employee", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", "Studio")
                        .WithMany("Employees")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lumora.Domain.Entities.Studio.ValueObjects.EmployeeRole", "EmployeeRole", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Employee Role Type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Employee Role Value");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("EmployeeRole")
                        .IsRequired();

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("StudioTags", b =>
                {
                    b.HasOne("Lumora.Domain.Entities.Identity.StudioProfile", null)
                        .WithMany()
                        .HasForeignKey("StudiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumora.Domain.Entities.Tag.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Event", b =>
                {
                    b.Navigation("Inquiries");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Event.Inquiry", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.ConsumerProfile", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Inquiry");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.StudioProfile", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Inquiries");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Lumora.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("ConsumerProfile");

                    b.Navigation("StudioProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
